### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by Shanmukh-C** [giandbt/synboost#10]
Hello
On downloading processed dataset from  http://robotics.ethz.ch/~asl-datasets/Dissimilarity/data_processed.tar  
 logit_distance  folder is missing in  road_anamoly dataset folder .Could you please  update it. In repo you have mentioned you will be releasing a script for preprocessing the dataset  is it ready?

**Comment by pswena** [comment]
> Hello On downloading processed dataset from http://robotics.ethz.ch/~asl-datasets/Dissimilarity/data_processed.tar logit_distance folder is missing in road_anamoly dataset folder .Could you please update it. In repo you have mentioned you will be releasing a script for preprocessing the dataset is it ready?

the author has updated the dataset in the closed issues, you can find the answer there.

**Comment by giandbt** [comment]
As pswena mentioned, you can find the answer here: https://github.com/giandbt/synboost/issues/4
