### ISSUE TITLE
How to remove data generator for ablation studies?

### ISSUE THREAD

**Issue by Kargnin** [giandbt/synboost#12]
Will we have to run files within this [folder](https://github.com/giandbt/synboost/tree/master/image_dissimilarity/data) except void_correction.py and recreate the dataset ?

If we are not using the proposed method of data generation which other method are we supposed to use(if any)?

**Comment by giandbt** [comment]
Hey Kargnin, I'm not sure I understand the question. If you are trying to remove the data generator, you can ignore whichever input data you don't want to use (re-synthesis, priors, or switched labels). 

If the question is how to generate the data, follow the [data preparation folder](https://github.com/giandbt/synboost/tree/master/data_preparation) for priors, semantic and synthesis. For switching labels, you can use this [file](https://github.com/giandbt/synboost/blob/master/image_dissimilarity/data/create_unknown_examples.py)

Let me know if this help or if it doesn't answer your question, can you give more details what you want to do

**Comment by Kargnin** [comment]
![image](https://user-images.githubusercontent.com/60797360/144402232-ca72b0e7-aeca-47ac-84d8-5dc5fa3aad67.png)
Exactly which data should we use for highlighted ablation study?

**Comment by giandbt** [comment]
You only need to use the original image (from Cityscapes), the segmentation map and the synthesized image. This will be the same data as shown in the Image Resynthesis paper (Detecting the unexpected via image resynthesis, citation 24 in our paper). The only difference is the dissimilarity network architecture (the data is all the same)

**Comment by Kargnin** [comment]
That clarifies the doubt, thanks a lot for very quick responses and congratulations for the amazing paper.
