### ISSUE TITLE
Referring to issue #9 

### ISSUE THREAD

**Issue by Shanmukh-C** [giandbt/synboost#13]
Hello,
I could not find seperate dataset for validation and testing. As even the validation dataset is same as test_dataset3 (fs lost and found). And as far as I have understood with the datasets provided in the repo we can reproduce only table2.

I would be grateful if you provide the dataset which you used to find metric in table1.
Thank You

**Comment by giandbt** [comment]
Hi Shanmukh, 

The results in table 1 are directly coming from our [Fishyscapes submission](https://fishyscapes.com/results). This benchmark only gives you limited validation data (the one used in table 2) and holds out the rest for the test side (we do not get to see the data). 

As such, we never had the test data used for table 1. We just submitted our code in the Fishyscapes website (in the right format) and they told us what was our results for each metric. 

You can see the [Fishyscapes paper](https://link.springer.com/content/pdf/10.1007/s11263-021-01511-6.pdf) where they explained in detail why they do it like this 
```
To this end, we (i) only release a small validation set with
associated ground truth masks, while keeping larger test sets
hidden
```

**Comment by Shanmukh-C** [comment]
Thank You for a quick response , I will take a look at the paper.
Congrats for producing such an excellent paper !

**Comment by pswena** [comment]
> Hi Shanmukh,
> 
> The results in table 1 are directly coming from our [Fishyscapes submission](https://fishyscapes.com/results). This benchmark only gives you limited validation data (the one used in table 2) and holds out the rest for the test side (we do not get to see the data).
> 
> As such, we never had the test data used for table 1. We just submitted our code in the Fishyscapes website (in the right format) and they told us what was our results for each metric.
> 
> You can see the [Fishyscapes paper](https://link.springer.com/content/pdf/10.1007/s11263-021-01511-6.pdf) where they explained in detail why they do it like this
> 
> ```
> To this end, we (i) only release a small validation set with
> associated ground truth masks, while keeping larger test sets
> hidden
> ```

I'm sorry to bother you, could you upload your code which submitted to the Fisherscapers submission?
