### ISSUE TITLE
Dockerfile don't work

### ISSUE THREAD

**Issue by TobiasMei** [giandbt/synboost#3]
Hello,
i want to test the framwork.

But building a docker with help from the dockerfile, I get a error on following line:
https://github.com/giandbt/synboost/blob/4c9d8e00aa292f8481bc82ba34d4a7e68854f057/Dockerfile#L11

The error is
```
/bin/sh: 1: /miniconda/bin/conda: not found
The command '/bin/sh -c /miniconda/bin/conda init bash' returned a non-zero code: 127
```
So, I think something in the previous line at the installation of miniconda going wrong.
I tested it on Windows with Docker Desktop (Version: 3.2.2 / Engine: 20.10.5) and Ubunt 18.04 (Docker Version: 19.03.6). 
On both system I get the error, so I think this issue is not from docker-version or other dependencies.

So I want to ask how can i fix this?
Is it possible to make a update for the docker-file to fix this?

**Comment by giandbt** [comment]
Hello,
Glad that you are trying to test the system. Unfortunately, the Dockerfile was deprecated for quite a while and these errors might come from outdated miniconda interfaces. I will try to update it this week, but in the meantime feel free to try the code as in the README. 

Best,
Giancarlo

**Comment by giandbt** [comment]
At the end, I decide not to maintain the Dockerfile as there are alternatives to get the project running, and this repository is not actively being maintained. Apologies for any inconvenience
