### ISSUE TITLE
Missing logit_distance folder in road_anomaly

### ISSUE THREAD

**Issue by ygjwd12345** [giandbt/synboost#4]
When I download your processed datasets. I face the  error :
 FileNotFoundError: [Errno 2] No such file or directory: './dataset/road_anomaly/logit_distance'

**Comment by chaoqinhuang** [comment]
I have the same problem. Please release the logit_distance data if you can.

**Comment by giandbt** [comment]
Sorry for the late response, I will check the whole dataset but if the problem is just road anomaly, you can find the files here: https://drive.google.com/file/d/10JKx5kvuFeyYMjlkoKyTOpU6mSMhAuus/view?usp=sharing
