### ISSUE TITLE
load pretrained weight didn't work

### ISSUE THREAD

**Issue by Yiru1103** [giandbt/synboost#5]
Hallo,

i want to use the synthesis netzwork to generate the realistic images of dataset Cityscapes using semantic map. but the pretrained weight of the synthesis module didn't match. 

hier is the error file:
./synbost-try/image_synthesis/util/util.py

line 227 net.load_state_dict(weights)

*** RuntimeError: Error(s) in loading state_dict for CondConvGenerator:
	size mismatch for fc.weight: copying a param with shape torch.Size([32768, 256]) from checkpoint, the shape in current model is torch.Size([1024, 36, 3, 3]).
	size mismatch for fc.bias: copying a param with shape torch.Size([32768]) from checkpoint, the shape in current model is torch.Size([1024]).

Do you knwo the reason? I didn't change any parameters.

Thank you for your help.

Best Regards
Yiru

**Comment by jinhuan-hit** [comment]
Hi, maybe you can check the network using Netron. By the way, I can't download the demo_files.tar from the link. Would you mind sharing the file? Thanks!

**Comment by giandbt** [comment]
It seems this is an error from the synthesis network. Our implementation comes directly from https://github.com/xh-liu/CC-FPSE, so if you just want to create realistic images, I would recommend starting there. 

Looking at the error itself, it seems the configuration of the network for the fully connected layer is off. You can check an example of how I create the synthesis images here: https://github.com/giandbt/synboost/blob/master/data_preparation/data_preprocess.py

Then, check what are the options I have define and make sure it matches yours

**Comment by Yiru1103** [comment]
> Hi, maybe you can check the network using Netron. By the way, I can't download the demo_files.tar from the link. Would you mind sharing the file? Thanks!

i can't download the demo_file.tar neither.

**Comment by Yiru1103** [comment]
> It seems this is an error from the synthesis network. Our implementation comes directly from https://github.com/xh-liu/CC-FPSE, so if you just want to create realistic images, I would recommend starting there.
> 
> Looking at the error itself, it seems the configuration of the network for the fully connected layer is off. You can check an example of how I create the synthesis images here: https://github.com/giandbt/synboost/blob/master/data_preparation/data_preprocess.py
> 
> Then, check what are the options I have define and make sure it matches yours

thank you, i'll try.

**Comment by pswena** [comment]
> Hallo,
> 
> i want to use the synthesis netzwork to generate the realistic images of dataset Cityscapes using semantic map. but the pretrained weight of the synthesis module didn't match.
> 
> hier is the error file: ./synbost-try/image_synthesis/util/util.py
> 
> line 227 net.load_state_dict(weights)
> 
> *** RuntimeError: Error(s) in loading state_dict for CondConvGenerator: size mismatch for fc.weight: copying a param with shape torch.Size([32768, 256]) from checkpoint, the shape in current model is torch.Size([1024, 36, 3, 3]). size mismatch for fc.bias: copying a param with shape torch.Size([32768]) from checkpoint, the shape in current model is torch.Size([1024]).
> 
> Do you knwo the reason? I didn't change any parameters.
> 
> Thank you for your help.
> 
> Best Regards Yiru

May I ask you a question? I want to ask you How to set the dataroot parameter in the file test_cityscapes.sh? I just want to use the pretrained_model to test the Cityscapes dataset, but I don't know the dataroot mean? Is it the output of the segmentation model? I would be very grateful if you could reply to me. Thanks
