### ISSUE TITLE
Download demo_files

### ISSUE THREAD

**Issue by jinhuan-hit** [giandbt/synboost#6]
Thanks for sharing the solid work! I can't download the demo_files and would you mind share it using GoogleDrive?

**Comment by giandbt** [comment]
Hey jinhuan-hit, I checked the download link and everything seems to be working. The problem is that all the files and data is about ~30GB so don't have enough space to add it to my personal drive. That's why I'm using a lab server.

**Comment by jinhuan-hit** [comment]
Thanks for your kind reply! I have already downloaded the model.tar successfully following README.
