### ISSUE TITLE
Preprocessing training data

### ISSUE THREAD

**Issue by TobiasMei** [giandbt/synboost#7]
Hello,

I want to understand the preprocessing of the cityscapes dataset to deploy it on a custom dataset.
Since this part is sparsely documented, I have some question. 

In the provided prepossessed  dataset (http://robotics.ethz.ch/~asl-datasets/Dissimilarity/data_processed.tar) are semantic and synthesized images. 
As far as I could follow, the semantics are created with the python file "create_unknown_examples.py" and not with the segmentation network?
With the temp folder created with this script, the synthesized images are created?
So then my observations right, the segmentation network is needed for the hole pipeline to make predictions on new pictures, but not for the training of the dissimilarity network.

I haven't found a python script for creating the logit-distance, mae-features and entropy. How did you calculate them?

Have i forgotten a step, that is needed to create the datasets?

**Comment by chensongloose** [comment]
Hello @TobiasMei, I also want to use custom datasets. Can you tell me how you prepare dataset?
Looking forward to your reply
